# Generated by Django 4.2.2 on 2023-06-30 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_manager_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manager',
            name='rol',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Manager',
        ),
    ]
